invenio_cli/cli.py

- Make the ``--flavour`` argument optional.
- Change CLI configuration to the root in order to allow other commands to obtain it.

init: make flavour optional and use .invenio config file

---

invenio_cli/cli.py
invenio_cli/utils.py

- Allows installing pre (alpha) releases
- Converst container creation into a non-blocking operation
Closes https://github.com/inveniosoftware/invenio-cli/issues/19

19 non blocking fg

---

invenio_cli/version.py

closes https://github.com/inveniosoftware/invenio-cli/issues/26

release: v1.0.0a2

---

invenio_cli/utils.py
invenio_cli/version.py

- Pull cookiecutter from tag
closes https://github.com/inveniosoftware/invenio-cli/issues/29

Release v1.0.0a3

---

invenio_cli/helpers/scripts.py
invenio_cli/version.py

Closes https://github.com/inveniosoftware/invenio-cli/issues/61

release v1.0.0a6

---

invenio_cli/helpers/scripts.py

Changes:
* Some parts in the dev mode were not correctly fixed in the previous merge.
NOTE: This also points out the lack of tests... In January we should really push to have tests once we have the command naming fixed.

scripts: fix logging in dev mode

---

invenio_cli/cli.py
invenio_cli/helpers/cookicutter_config.py
invenio_cli/helpers/scripts.py

Needs https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/33 merged first.

docker: use 1 dockerfile

---

invenio_cli/helpers/scripts.py

- requires https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/34 to be merged in
- `--containers` version is taken care of by the Dockerfile in cookiecutter (PR above)
- close #81

build: symlink templates/ for --local

---

README.rst
invenio_cli/cli.py
invenio_cli/helpers/commands.py
invenio_cli/helpers/docker_helper.py
setup.py
tests/test_helpers/test_commands.py
tests/test_helpers/test_dockerhelper.py

Tomorrow I should be able to do most of the container work and removal of old commands / dependencies. Might also rename some stuff then.
- Closes #67 
The following were closed by prior PRs:
- Closes #72 
- Closes #73

[follows from #104] Wrap-up --local flow

---

invenio_cli/cli.py
invenio_cli/helpers/cli_config.py
invenio_cli/helpers/commands.py
invenio_cli/helpers/cookiecutter_wrapper.py
tests/test_helpers/test_cli_config.py
tests/test_helpers/test_commands.py
tests/test_helpers/test_cookiecutter_wrapper.py

closes #100 
closes #75 
closes #82

Cookiecutter improvements: version, cookiecutter, folder error

---

invenio_cli/helpers/cookiecutter_wrapper.py

Point to (be) released cookiecutter branch

cookiecutter: set to v0.6.0

---

invenio_cli/helpers/cookiecutter_wrapper.py
invenio_cli/version.py

Release v0.10.0

---

invenio_cli/helpers/commands.py
tests/test_helpers/test_commands.py

Changes:
* Adds `demo` command for containerized versions
Closes https://github.com/inveniosoftware/invenio-cli/issues/115

containerize: add demo command

---

invenio_cli/version.py

closes https://github.com/inveniosoftware/invenio-cli/issues/118

release: v0.10.1

---

invenio_cli/version.py

release: v0.11.1

---

invenio_cli/version.py

release: v0.14.0

---

invenio_cli/helpers/cookiecutter_wrapper.py
invenio_cli/version.py

Will wait for tomorrow to merge this, so that someone else (hint hint @zzacharo ?) has time to to do some testing too.

Release v0.16.0

---

.gitignore
invenio_cli/cli.py
invenio_cli/helpers/commands.py
invenio_cli/helpers/docker_helper.py
tests/test_helpers/test_commands.py

Cli destroy command

---

invenio_cli/cli.py
invenio_cli/helpers/commands.py
tests/test_helpers/test_commands.py

Closes https://github.com/inveniosoftware/invenio-cli/issues/109

Added stop command for containers

---

invenio_cli/helpers/docker_helper.py

Removing unused functions

---

invenio_cli/cli.py

* Adds short versions of e.g. -v for --verbose.

cli: add short versions of options

---

invenio_cli/helpers/cookiecutter_wrapper.py
invenio_cli/version.py

**Do not merge until November release**

november release

---

invenio_cli/commands/assets.py

* Closes https://github.com/inveniosoftware/invenio-cli/issues/189

assets: fixes error in npm watching call

---

setup.py

* Closes https://github.com/inveniosoftware/invenio-cli/issues/188

setup: fixes click version error

---

invenio_cli/commands/assets.py

Superseeds https://github.com/inveniosoftware/invenio-cli/pull/209
Closes #208
authored by @siddharth1010

Fixed bug #208

---

invenio_cli/cli/install.py
invenio_cli/commands/install.py

install: allow locking dependencies on first installation

---

invenio_cli/helpers/cookiecutter_wrapper.py
invenio_cli/version.py

Merge and release this to make the January release public.

release v0.21.0

---

invenio_cli/commands/assets.py

cli: fix issue with not being able to install fresh react module

---

invenio_cli/commands/services_health.py
invenio_cli/helpers/cli_config.py
tests/commands/conftest.py

Fixes https://github.com/inveniosoftware/invenio-cli/issues/231.

global: clean up references to sqlite

---

invenio_cli/cli/utils.py
invenio_cli/commands/services.py
invenio_cli/commands/steps.py
invenio_cli/helpers/process.py

Fixes https://github.com/inveniosoftware/invenio-cli/issues/221

Add skippable option to FunctionStep to allow failing without giving error

---

invenio_cli/cli/utils.py

utils: fix step naming

---

invenio_cli/cli/packages.py
invenio_cli/commands/packages.py

implement cli commands for update and upgrade functionalities.
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/657

invenio-cli: 

---

invenio_cli/commands/requirements.py

Add check requirement step for ImageMagick.

Requirements

---

invenio_cli/cli/cli.py
invenio_cli/commands/upgrade.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/854

cli: Adds migration script to upgrade

---

invenio_cli/cli/packages.py
invenio_cli/commands/packages.py
invenio_cli/helpers/cli_config.py

Include a command to update invenio-app-rdm.
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/849

global: add command to update invenio-app-rdm package

---

invenio_cli/commands/upgrade.py

partially closes https://github.com/inveniosoftware/invenio-rdm-records/issues/636

commands: split rebuild index form records and communities

---

invenio_cli/helpers/cookiecutter_wrapper.py
invenio_cli/version.py

**[DO NOT MERGE]** Until the release candidate is fully tested, since this will mean any user installing from scratch will get it

[RC] bump cookiecutter and release

---

invenio_cli/commands/local.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/782
* closes https://github.com/inveniosoftware/invenio-cli/issues/202
* depends on https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/182

commands: remove SITE_HOSTNAME

---

invenio_cli/commands/services.py
invenio_cli/helpers/cli_config.py
tests/commands/conftest.py

* Uses the ``file_storage`` configuration variable to define the
corresponding file path for the default location. (closes #96)

services: allow for different file locations

---

invenio_cli/commands/requirements.py
tests/commands/test_requirements.py

Not sure what's the current board so I asked for review :)

fix check requirements

---

invenio_cli/helpers/cli_config.py
invenio_cli/version.py
tests/helpers/test_cli_config.py

- config: fix instance path regression
- release: v1.0.2

fix instance path regression

---

invenio_cli/commands/install.py
invenio_cli/commands/packages.py

Ah well, I got tired of this not being the case, so I just fixed it.
- closes #213

install: install development dependencies with --dev

---

LICENSE
invenio_cli/cli/cli.py
invenio_cli/helpers/cookiecutter_wrapper.py

closes https://github.com/inveniosoftware/invenio-cli/issues/280

cli: add --no-input and --config options for unsupervised init (closes #280)

---

invenio_cli/cli/cli.py
invenio_cli/commands/requirements.py

Closes https://github.com/inveniosoftware/invenio-cli/issues/291
This PR aims to make the `invenio-cli check-requirements [--development]` command a bit more consistent.

Update `check-requirements` command

---

invenio_cli/cli/containers.py
invenio_cli/cli/packages.py
invenio_cli/cli/services.py
invenio_cli/commands/services.py
invenio_cli/commands/services_health.py
invenio_cli/commands/upgrade.py
invenio_cli/errors.py
invenio_cli/helpers/cli_config.py
invenio_cli/helpers/cookiecutter_wrapper.py
tests/helpers/test_cli_config.py

This pull request removes elasticsearch 6 support and adds support for Opensearch 1.
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under …

remove support for elasticsearch6, add opensearch instead

---

invenio_cli/cli/cli.py
invenio_cli/commands/local.py

This PR adds the parameter --celery-log-file to the run command.
With this parameter it is possible to specify a file as the output for the
celery worker log messages. This reduces the log message noise of the
invenio-cli run command.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-cont …

logging: add parameter --celery-log-file

---

invenio_cli/cli/assets.py
invenio_cli/cli/packages.py
invenio_cli/commands/local.py
invenio_cli/commands/packages.py
invenio_cli/commands/steps.py
invenio_cli/helpers/process.py

With this PR two new parameters are added. Both could be used to reduce the
logging information by redirecting the output to files.
**Reminder**
1. You license your contribution under the same …

add pip and node logfile parameter

---

invenio_cli/cli/cli.py
invenio_cli/commands/local.py
invenio_cli/helpers/cookiecutter_wrapper.py

* add possibility to use ILS flavour in  'invenio-cli init' command
* specify cookiecutter-invenio-ils link for ILS flavour
* closes https://github.com/inveniosoftware/invenio-cli/issues/309

add support for managing ILS instance

---

invenio_cli/commands/containers.py
invenio_cli/commands/services.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1989

services: remove static pages from setup

---

invenio_cli/commands/containers.py
invenio_cli/commands/services.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1989

fixtures: add rdm fixtures

---

invenio_cli/commands/containers.py

translations: fixed issue with empty translations folder

---

invenio_cli/commands/requirements.py

Checking of development requirements with (documented) Node.js V16 installed leads to
```
Pre requisites not met.
Errors: Node wrong version.Got [16, 17, 1] expected 14
```
Same problem with npm. This PR upgrades the check to the versions mentioned in the docs.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …

Fix check of development requirements

---

invenio_cli/commands/local.py

The command `invenio-cli install` returns success all the time, even if parts of the process fails. There is a `#FIXME` in the code that this pull request addresses
**Reminder**
1. You license …

Checking the return value in invenio-cli install

---

CHANGES.rst
invenio_cli/__init__.py

Please describe briefly your pull request.
**Reminder**
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …

release: v1.2.0

---

CHANGES.rst
invenio_cli/__init__.py
invenio_cli/commands/requirements.py
invenio_cli/helpers/cookiecutter_wrapper.py

- **dependencies: update for invenio-app-rdm v12**
- **release: v1.5.0**

v12 release

---

invenio_cli/commands/services.py
invenio_cli/commands/services_health.py
invenio_cli/helpers/cli_config.py
invenio_cli/helpers/docker_helper.py

- service: add configurable host and port for search
- services: change from bash to sh
- chore: remove unused statements
- services: rely on self.local for stop and destroy

make container alpine ready

---

invenio_cli/helpers/versions.py

Add support for detection of the app-rdm version from the pipfile "ref" field. This is needed if folks are doing local development of app-rdm and using pipenv.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Reminder**
1. You license your contribution under the same terms as the …

versions: support ref in pipfile
