- invenio_cli/cli.py
- invenio_cli/utils.py
- When executing the build in "semi-prod" the app and the base images needed to be explicitly requested (i.e. add ``--base`` and ``--app`` flags). It is better to have them by default and allow ``skip`` on them.
- There was a bug on the image name, it was containing the whole cwd path instead of just the project name. A new property was added.
- The destroy command was not removing the volumes. Kudos to @fenekku, for the reminder :)
> global: several bug fixes

- invenio_cli/cli.py
- invenio_cli/helpers/__init__.py
- invenio_cli/helpers/cookicutter_config.py
- invenio_cli/helpers/docker_helper.py
- invenio_cli/helpers/scripts.py
- setup.py
Changes:
* Executes setup commands inside the web_api container for `prod` version.
* Differences between docker-compose lower and greater than 1.21 (special characters accepatance).
* Adds command for data population (WIP in prod version)
> demo: add command to create demo records and fix prod setup

- invenio_cli/cli.py
- invenio_cli/helpers/__init__.py
- invenio_cli/helpers/docker_helper.py
- invenio_cli/helpers/log.py
- invenio_cli/helpers/scripts.py
Changes:
* Remove unused loglevel attribute accross the whole code.
* Set default loggers to level `INFO` and handle the level by checking opperation status code when possible.
* Opened issue to try to handle the level in a better way for output piped from `stdout` and `stderr`. https://github.com/inveniosoftware/invenio-cli/issues/48 Moved to January board, not priority.
* Encapsulated `verbose` and `logfile` into attribute `logging_conf`.
Closes https://github.com/inveniosoftware/invenio-cli/issues/47
> global: refactor logging attributes

- invenio_cli/cli.py
- invenio_cli/helpers/__init__.py
- invenio_cli/helpers/scripts.py
- setup.py
Changes:
- Adds an `assets` command.
- Allows collecting statics
- Allows building with webpack
- Allows both of the previous actions at the same time.
Caveats:
- The `webpack buidlall` part displays the full logs on the terminal. It is due to some internal part of it printing to stdout and now allowing control. It will be most likely be fixed by https://github.com/pallets/click/issues/737 and/or when we manage to fix https://github.com/inveniosoftware/invenio-cli/issues/66 using an interpreter.
- Not implemented for `--prod`. Since it requires a restart of uwsgi. I assume the workflow for this would be to `update` statics and rebuild the app container (not base) if not. All after having tested/modified in a `--dev` environment. (No ?)
Closes …
> command: add assets command to build statics and/or assets independently

- invenio_cli/cli.py
- invenio_cli/helpers/docker_helper.py
- invenio_cli/helpers/scripts.py
Changes:
- `--dev` by `--local`. Chose *local* over *venv* because it can also potentially install in a bare system (without a venv).
- `--prod` by `--containers`.
Requires: https://github.com/inveniosoftware/invenio-cli/pull/69
Closes: https://github.com/inveniosoftware/invenio-cli/issues/70
> global: environment naming

- invenio_cli/cli.py
- invenio_cli/helpers/scripts.py
Changes:
- Adds `--stop-containers` to setup and demo commands
- Conditions the stop of the containers to the previous flag being passed. Defaults to false (no stop).
Closes https://github.com/inveniosoftware/invenio-cli/issues/68
> setup/populate: stop containers only when specified

- setup.py
Why? The CLI is crashing in local mode due to a old/ancient dependency on cookiecutter in `invenio-base` (see https://github.com/inveniosoftware/invenio-base/pull/146). It sets no upper limit, while `invenio-cli` requires `<1.7.0`.
Invenio CLI is installed correctly, however after `build --local` cookiecutter gets installed with a higher version (1.7.0) that collides with the *setup.py* of `invenio-cli` and therefore no other command works.
Note: This might only happen if you install both `invenio-cli` and the local instance in **the same venv**, which is the case in some cases.
I have checked [cookiecutter release history](https://cookiecutter.readthedocs.io/en/1.7.0/HISTORY.html) and it does not seem to be any issues affecting us.
Retrospective: We should really standarize how to …
> dependencies: bump cookiecutter

- .travis.yml
- invenio_cli/cli.py
- invenio_cli/helpers/__init__.py
- invenio_cli/helpers/cli_config.py
- invenio_cli/helpers/commands.py
- invenio_cli/helpers/cookiecutter_wrapper.py
- invenio_cli/helpers/filesystem.py
- tests/test_helpers/test_cli_config.py
- tests/test_helpers/test_commands.py
This is the first step in refactoring the cli:
- Only deals with init and build --local for now
- Illustrates relatively well how I will proceed with the rest of the commands: feedback now would be greatly appreciated to help orient things
- Removed the verbose flag for now to keep things a little more scoped. I do not mind at all adding it back later. 
- It adds tests: I decided to principally go the mocking way (there is temporary file creation for the cli config file only). I am experimenting here, if you've had prior experience testing similar things and have found productive approaches let me know. Good thing: tests are fast and cover a lot of things. Bad thing: confidence level is not as high given that some mocked calls expect specific input / return specific output in reality and …
> init + build --local refactor

- invenio_cli/cli.py
- invenio_cli/helpers/commands.py
- tests/test_helpers/test_commands.py
Changes:
* Adds `pre` to containerize command to allow locking pre-releases only when specified.
Closes https://github.com/inveniosoftware/invenio-cli/issues/114
> containerize: make pre-release deps lock optional

- invenio_cli/helpers/commands.py
- invenio_cli/helpers/cookiecutter_wrapper.py
- invenio_cli/version.py
- tests/test_helpers/test_commands.py
- tests/test_helpers/test_cookiecutter_wrapper.py
Needed for custom vocab to work in development mode.
Also bump the version BUT :warning: this needs the cookiecutter PR https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/59 to be merged first, so that its version can be used.
> cli: symlink app_data + bump version

- invenio_cli/helpers/cli_config.py
- setup.py
- tests/test_helpers/test_cli_config.py
- tests/test_helpers/test_filesystem.py
Closes https://github.com/inveniosoftware/invenio-cli/issues/121
Changes:
- `project_dir` is calculated based on where the cli is called from. This would have implications on how the logs file is set. It is now a relative path and should be added the `project_dir` as base. However, as far as I can see the logging config is not being created.
- Relaxes the dependency on click version. Invenio does not have it pin and it gave a pipenv collision with the new 7.1.1 released.
Tested:
- local: Ok
- containers: Ok
**Question**: Shall we follow the same approach with `instance_path` since it is caluclated for each case, is it worth having it written? I think we can just assume is the current env. Meaning, we keep calculating as till now, but we dont write it. It will be calculated on start up.
> config: use cwd as project_dir

- invenio_cli/cli.py
- invenio_cli/helpers/commands.py
- tests/test_helpers/test_commands.py
May be of use in respect of #97 - only accepts host and port, but these are probably the most common things to tweak?
> allow 'run' command to pass --host/-h and --port/-p to invenio

- invenio_cli/helpers/commands.py
- tests/test_helpers/test_commands.py
Celery 5.0.0 changed the order of cli arguments.
`--app` is no part of the worker subcommand, it belongs to the parent command.
A invocation of would look like `celery --app=proj worker ...`
See #160
> Fix worker invokation for celery >= 5.0.0

- invenio_cli/helpers/commands.py
- tests/test_helpers/test_commands.py
**Open question**
- Do we assume that there is always a port and host? e.g. if I want to run in `mysite.com` I also provide the port (no 443 assumptions if `port == None`)
> commands: add site hostname config when running local

- invenio_cli/cli.py
- invenio_cli/helpers/cli_config.py
- invenio_cli/helpers/commands.py
- invenio_cli/helpers/services.py
- tests/test_helpers/test_commands.py
**Requires**
- https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/124
- Change containers restart policy to `unless-stopped`.
- Remove unused services from `docker-services.yml`: flower, kibana, lb
**Changes**
- Adds healthchecks. Closes #53 
- Elasticseach healthcheck takes into account status `yellow` (not `green`). Since it uses a single node, ES is `yellow` because there is risk of loosing data (i.e. no proper sharding/replication). When fully *not ready* status is`red`.
- Status command to check the services are up and running (i.e. `invenio-cli status`). Currently it is only a *generic* command, which works both for local and containerize. However, it only checks redis, es and db (i.e. no web apps, nor workers) because the healthchecks are not implemented. Closes #175 …
> improve services and commands

- LICENSE
- invenio_cli/commands/requirements.py
closes #214 
* previously, 'python' would be called to determine the version, which
is symlinked to 'python2' on some systems (e.g. Debian 10)
* python2 apparently prints its version information to stderr instead of
stdout
* instead of calling a 'python --version' subprocess, we now check the
python version executing 'invenio-cli', as the latter will create a
new virtualenv with the stated python version for invenio rdm (via
pipenv) anyway
> Change Python version check

- invenio_cli/commands/containers.py
- invenio_cli/commands/services.py
closes inveniosoftware/invenio-rdm-records#347
* allows the cration of required vocabularies without creating demo records
this will likely require a dependency bump for `invenio-rdm-records` somewhere (`invenio-app-rdm`, and `cookiecutter-invenio-rdm`?)
otherwise, `invenio-cli setup` will fail due to the command `invenio rdm-records vocabularies` being unknown
> cli: separate vocabulary creation from demo record creation

- invenio_cli/commands/containers.py
- invenio_cli/commands/services.py
* the rdm-records cli command for setting up the fixtures has
previously been called vocabularies, but it has been renamed
since it does more than only set up vocabularies
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/395
> setup: call rdm-records fixtures instead of vocabularies

- invenio_cli/commands/requirements.py
Fixes https://github.com/inveniosoftware/invenio-cli/issues/196. A couple of logging messages were also fixed to report the correct name of the executables being checked.
Example of the previous behaviour when the `docker-compose` executable was not found in the path: See https://github.com/inveniosoftware/invenio-cli/issues/196.
New behaviour:
This was applied to the `docker` and `docker-compose` version check steps but could be extended also to the other ones (e.g. node).
> Show proper errors when docker and docker-compose executables are not found

- invenio_cli/commands/requirements.py
Fixes https://github.com/inveniosoftware/invenio-cli/issues/227 doing a couple of things:
- Sets the `exact`flag to True in the node version checking, thus moving the requirement condition from ">=14" to "==14"
- Since the `exact` flag is currently implemented to have a global effect (e.g. `exact` with `major=14` will fail with any 14.x.x since it expects exact values for minor and patches too), the proposed change makes the check logic consider `-1`(the default value for unspecified numbers) as a * wildcard. This means that `exact` with `major=14` now passes with any 14.x.x, but fails if a (mismatching) minor is specified.
I can't think of any other solution not requiring the rewrite of the entire version checking logic to accept actual version ranges and wildcards so I think this is an …
> requirements: require exact node version 14

- CONTRIBUTING.rst
README only has usage instructions, but there are no mentions on how to correctly contribute on the tool itself. This PR should fix this by linking to the "Tools" paragraph of the invenio rdm maintainers guide that explains how to do this
> Link inveniordm guide for setting up an environment to work on the module itself

- invenio_cli/commands/requirements.py
- invenio_cli/commands/steps.py
- tests/commands/test_steps.py
closes https://github.com/inveniosoftware/invenio-cli/issues/249
A warning always get's an exit code `> 0`. The difference with an error is that it should not exit the program.
> cli: warning messages do not exit

- invenio_cli/cli/cli.py
- invenio_cli/cli/utils.py
* Avoids creating an extra Pipenv file when running `calculate_instance_path`
closes https://github.com/inveniosoftware/invenio-cli/issues/260
> cli: ensure pipenv command is running inside created project dir

- invenio_cli/commands/steps.py
- closes #257 
- 
The logic was incorrect:
- Previous: a command marked as `skippable` (i.e. soft check) was being shown as a warning independently of the status code (i.e. fail or not)
- Current: a command marked as `skippable` (i.e. soft check) is being shown as warning only if the check fails.
> steps: output logic for function step execute with warning

- setup.py
The requirement `docker<5` caused version mismatches (reported as warnings from `pip`, without noticeable consequences) on some Linux distributions (e.g. Manjaro) with docker-compose from the package manager.
> Allow docker 5.x as dependency

- invenio_cli/helpers/docker_helper.py
Makes version check behave correctly for docker compose v2 and beyond. Resolves #268
> helpers: make version number work for docker compose v2

- .gitignore
- invenio_cli/cli/cli.py
- invenio_cli/cli/install.py
- invenio_cli/cli/services.py
- invenio_cli/cli/utils.py
- invenio_cli/helpers/cli_config.py
- invenio_cli/version.py
- run-tests.sh
- tests/helpers/test_cli_config.py
closes #130
To summarize: as part of a team I want to clone the instance repository and run `invenio-cli install` ... without having to artificially create a `.invenio.private` with a path to a virtualenv that I also need to create. This had to be done before because these steps were done by `invenio-cli init` which isn't run because my teammate already ran it (I am cloning the result of that command afterall). This is also handy even without teammates, if one is cloning the repo on a different computer.  
This PR addresses that by relying on the in-memory project directory directly (no need to look-up the `.invenio.private` file) and the fact that `invenio-cli install` sets the instance location. Even though we technically still rely on .invenio.private for it, it should really be …
> config: remove need for pre-existing .invenio.private per team member

- setup.py
Allow the 8.0.X releases of `click` (which is required by newer releases of `black`), as the change log doesn't show any breaking changes that'd be relevant for us: https://click.palletsprojects.com/en/8.0.x/changes/
> setup: bump click dependency

- invenio_cli/commands/services.py
- closes #305 
Shell output:
```
Putting templates...
[####################################]  100%
Creating custom fields for records...
Creating custom fields...
Created all custom fields!
Creating custom fields for communities...
No custom fields were configured. Exiting...
Updating service setup status (True)...
```
Since no CF were configured for communities it only did it for records. Checked with postman and the field is in the mapping.
Since the field is not `required` the demo records were created without a problem.
> services: add custom fields init to setup

- invenio_cli/commands/requirements.py
Follows up https://github.com/inveniosoftware/docs-invenio-rdm/pull/379.
`invenio-cli check-requirements` now checks if git is installed, without paying attention to the version (similar to what we do with imagemagick).
I added the step in the `development` requirements, but I'm not super sure about it, since `git` is required even for the `invenio-cli init rdm -c <version>` command, which is suggested in both [installation methods](https://inveniordm.docs.cern.ch/install/), local and containers.
> Check for git as requirement

- invenio_cli/cli/assets.py
- invenio_cli/cli/cli.py
- invenio_cli/cli/containers.py
- invenio_cli/cli/services.py
- invenio_cli/cli/utils.py
- invenio_cli/commands/assets.py
- invenio_cli/commands/containers.py
- invenio_cli/commands/install.py
- invenio_cli/commands/local.py
- invenio_cli/commands/services.py
- invenio_cli/commands/services_health.py
- invenio_cli/helpers/docker_helper.py
- invenio_cli/helpers/process.py
The `click` context is injected in many places (e.g. `click.echo`) but it should instead be only used in the `cli` module, not in `commands` module. With current code, is quite easy to end up with circular imports and it is not easy to make the code testable.
Tip: avoid global context (`import click`) as much as possible where it is not needed.
Some funcs are aware of how they are called: they should not be. A func should have a clear API and the caller needs to take care of the response and take actions depending on the response.
> services: fix wait for services to start

- CHANGES.rst
- invenio_cli/__init__.py
- invenio_cli/cli/cli.py
- invenio_cli/cli/translations.py
- invenio_cli/commands/__init__.py
- invenio_cli/commands/containers.py
- invenio_cli/commands/services.py
- invenio_cli/commands/translations.py
- invenio_cli/helpers/cli_config.py
- setup.cfg
- closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/241
In the following image you can see:
- On the top left, extracted messages both from `./site` and `invenio.cfg`
- On the bottom left the part of the `container start ...` that corresponds to the catalog compilation
- On the right, InvenioRDM running on containerized version (alsto tested local and it's the same) with a translated string being shown.
**Pending**
- If the implementation is approved/merged. We should document it, since users still need to create catalogs for the desired language (that cannot be automated since we cannot know in advance which language/s the user wants).
---
@mb-wali This PR (along with one in cookiecutter) will enable users to add their own custom translations + translate strings …
> global: add support for translation commands

- invenio_cli/cli/utils.py
- invenio_cli/commands/services.py
- invenio_cli/helpers/process.py
It looks like this now:
```shell
Created required fixtures!
Compiling message catalog...
Traceback (most recent call last):
File "/Users/ppanero/.virtualenvs/instance-comm-perm/bin/pybabel", line 8, in <module>
sys.exit(main())
File "/Users/ppanero/.virtualenvs/instance-comm-perm/lib/python3.9/site-packages/babel/messages/frontend.py", line 1034, in main
return CommandLineInterface().run(sys.argv)
File "/Users/ppanero/.virtualenvs/instance-comm-perm/lib/python3.9/site-packages/babel/messages/frontend.py", line 960, in run
return cmdinst.run()
File "/Users/ppanero/.virtualenvs/instance-comm-perm/lib/python3.9/site-packages/babel/messages/frontend.py", line 198, in run
for errors in self._run_domain(domain).values():
File "/Users/ppanero/.virtualenvs/instance-comm-perm/lib/python3.9/site-pac …
```
> fix error message on catalog compilation command

- invenio_cli/commands/containers.py
- invenio_cli/commands/services.py
- setup.cfg
This is required in order for the statistics integration to work properly, because it relies on messaging via a message queue.
Needs some testing.
> Services: add 'declare queues' step to setup

- setup.cfg
Bumped up cookiecutter. 
I install `invenio-cli` on the global level, where I also want to use a newer cookiecutter version because of new features such as "private variables" in the template.
> chore: bump cookiecutter version upper bound

- invenio_cli/cli/cli.py
Very minor. Passing of time helped make it more apparent that this wasn't really clear. 
It's `files` because .invenio and .invenio.private are written out.
> update init command print out

- invenio_cli/commands/requirements.py
- invenio_cli/commands/services_health.py
- invenio_cli/helpers/docker_helper.py
- tests/helpers/test_dockerhelper.py
* closes https://github.com/inveniosoftware/invenio-cli/issues/348
As described in https://github.com/inveniosoftware/invenio-cli/issues/348 `invenio-cli` internally uses the deprecated version 1x of `docker-compose` to orchestrate containers. This forces users to install the old version alongside the newer version of `docker compose`. This pull request changes the underlying subcommands to use the new syntax.
**Reminder**
1. You license your contribution under the same terms …
> Switch to `docker compose` v2 

- invenio_cli/commands/services.py
Added `INSTANCE_PATH` as an environment variable on services setup.  The variable can be used by docker services if needed (e.g. to setup a volume)
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1728
> services: add instance path to env on setup

- invenio_cli/cli/services.py
Small typo in the docstring that gets printed in the --help command. 
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you …
> Fix typo in docstring

- .github/workflows/pypi-publish.yml
- .github/workflows/tests.yml
- invenio_cli/cli/assets.py
- invenio_cli/cli/install.py
- invenio_cli/cli/packages.py
- invenio_cli/commands/assets.py
- invenio_cli/commands/commands.py
- invenio_cli/commands/install.py
- invenio_cli/commands/local.py
- setup.cfg
- tests/commands/test_local.py
- tests/helpers/test_env.py
* ``FLASK_ENV`` has been removed in Flask v2.3 and ``FLASK_DEBUG`` is
recommended instead.
* This also makes sure that with Flask v2.3+ debug mode features like hot reloading and assets linking works.
> global: replace FLASK_ENV with FLASK_DEBUG

- CHANGES.rst
- docs/conf.py
- invenio_cli/__init__.py
- invenio_cli/cli/cli.py
- invenio_cli/cli/install.py
- invenio_cli/cli/packages.py
- invenio_cli/cli/translations.py
- invenio_cli/cli/utils.py
- invenio_cli/commands/assets.py
- invenio_cli/commands/commands.py
- invenio_cli/commands/containers.py
- invenio_cli/commands/install.py
- invenio_cli/commands/local.py
- invenio_cli/commands/packages.py
- invenio_cli/commands/requirements.py
- invenio_cli/commands/services.py
- invenio_cli/commands/translations.py
- invenio_cli/commands/upgrade.py
- invenio_cli/helpers/__init__.py
- invenio_cli/helpers/cli_config.py
- invenio_cli/helpers/filesystem.py
- invenio_cli/helpers/package_managers.py
- setup.cfg
- tests/commands/test_containers.py
- tests/commands/test_local.py
- tests/helpers/test_cli_config.py
- tests/helpers/test_cookiecutter_wrapper.py
- tests/helpers/test_env.py
This is a variant of #383 with the `pnpm`/`rspack` stuff stripped out, and some squashed commits.
It only touches `uv`, since that's quite uncontroversial and works well enough already.
If you have a `Pipfile` in your project, then `pipenv` will be used by default.
If you have `pyproject.toml` and no `Pipfile`, then `uv` will be used by default.
If your use case is not satisfied by this auto-magic, then you can explicitly configure the package manager to use in `.invenio`:
```ini
[cli]
flavour = RDM
python_package_manager = uv
```
Note the lack of quotes around the value `uv`.
Currently, only `uv` and `pipenv` are supported as values.
> Implement `uv` as an optional python package management backend

- CHANGES.rst
- invenio_cli/__init__.py
- invenio_cli/commands/assets.py
- invenio_cli/commands/local.py
- invenio_cli/helpers/cli_config.py
- invenio_cli/helpers/package_managers.py
- setup.cfg
This PR is the frontend cousin of https://github.com/inveniosoftware/invenio-cli/pull/384 (which similarly enabled `uv` for python).
Note: This feature requires `flask-webpackext` v2.1.0
Similar to `uv`, `pnpm` can be enabled in `.invenio` (which is the "public" configuration file that is intended to be shared between developers via version control).
Unlike `uv`, there are (currently [1]) no artifacts in the project directory that would indicate whether `npm` or `pnpm` should be used and thus the fallback is simply `npm` (i.e. `pnpm` has to be explicitly configured).
Configuration in `.invenio`:
```ini
[cli]
flavour = RDM
logfile = /logs/invenio-cli.log
javascript_package_manager = pnpm
```
[1] this may change once the "reusable frontend lock file" logic gets merged as:
* `package.lock` …
> Enable PNPM (rspack is part of Invenio-Assets)

- CHANGES.rst
- invenio_cli/__init__.py
- invenio_cli/helpers/versions.py
This fixes the `invenio-cli check-requirements` being broken when using `pipenv` (`Pipfile`).
> Fix accidental creation of a tuple in version check

- invenio_cli/commands/install.py
This PR makes sure the instance path is updated correctly, even if the user has `editing_mode='vi'` set in their ipython config, so far resulting in funky instance paths like `.virtualenvs/mysite/var/instance$'\033'\[0\ q`, effectively breaking assets build.
Related issue: https://github.com/inveniosoftware/invenio-cli/issues/361
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> fix: vi editing_mode when updating instance path

- invenio_cli/helpers/versions.py
* `_from_pyproject_toml` had `invenio-app-rdm` as a hardcoded filter,
which caused issues for RDM projects that have migrated to `uv` and
`pyproject.toml`.
> versions: fix pyproject.toml app dependency version detection
